apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jenkins-ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.kubernetes.io/zone
        values:
          - ap-south-1a  # Replace with your exact AZ
