controller:
  persistence:
    enabled: true
    existingClaim: jenkins
    storageClass: ""
    size: 10Gi

  service:
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443
    securityContext:
    fsGroup: 1001
    runAsUser: 1001
    runAsGroup: 1001  
    port: 8080
    targetPort: http

  adminUser: admin
  adminPassword: admin

  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
