controller:
  image:
    tag: 2.516.1-jdk21
  adminUser: admin
  adminPassword: admin

  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest

  service:
    type: NodePort
    nodePortHttp: 30080
    nodePortHttps: 30443

  persistence:
    enabled: true
    existingClaim: jenkins
    storageClass: ""
    size: null
    accessMode: ReadWriteOnce

  podSecurityContext:
    fsGroup: 1000

  containerSecurityContext:
    runAsUser: 1000
