controller:
  installPlugins:
    - kubernetes:1.29.7
    - workflow-job:2.44
    - workflow-aggregator:2.7
    - credentials-binding:1.27
    - git:5.2.1

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  # 👇 This is crucial: allow pod scheduling on control-plane node
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""

  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"

  # 👇 Mount dynamic PVC
  persistence:
    enabled: true
    existingClaim: jenkins
    storageClass: jenkins-ebs-sc
    accessMode: ReadWriteOnce
    size: 10Gi

  serviceType: NodePort
  nodePort: 32000

agent:
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

persistence:
  storageClass: jenkins-ebs-sc
