controller:
  admin:
    username: admin
    password: admin@123

  serviceType: NodePort
  nodePort: 32000

  installPlugins:
    - kubernetes
    - git
    - workflow-aggregator
    - blueocean
    - credentials-binding
    - docker-workflow

  persistence:
    enabled: true
    existingClaim: jenkins
    storageClass: "-"

  resources:
    requests:
      cpu: "500m"
      memory: "800Mi"
    limits:
      cpu: "1"
      memory: "1.2Gi"

  JCasC:
    defaultConfig: true
    configScripts:
      kubernetes-agent-config: |
        jenkins:
          clouds:
            - kubernetes:
                name: "kubernetes"
                serverUrl: "https://kubernetes.default"
                namespace: "jenkins"
                jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
                jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
                containerCap: 10
                podRetention: never
                templates:
                  - name: "default-agent"
                    label: "k8s-agent"
                    containers:
                      - name: "jnlp"
                        image: "jenkins/inbound-agent:latest"
                        args: "${computer.jnlpmac} ${computer.name}"
                        ttyEnabled: true
                        resourceRequestCpu: "100m"
                        resourceRequestMemory: "256Mi"
                        resourceLimitCpu: "200m"
                        resourceLimitMemory: "512Mi"

agent:
  enabled: true
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
