controller:
  installPlugins: []
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

  serviceType: NodePort
  nodePort: 30080

  admin:
    username: admin
    password: admin

  persistence:
    enabled: true
    existingClaim: jenkins
    storageClass: ""
    size: null

  initContainers: []  # ✅ disables broken init script
